### ISSUE TITLE
Client don't work with 2.75

### ISSUE THREAD

**Issue by janstieler** [TrueCryer/blendermada_client#1]
Hi,
I installed the blendermada client on the last version and it doent displays any materials and on clicking preeview it displays an error:
![bildschirmfoto 2015-08-27 um 22 06 05](https://cloud.githubusercontent.com/assets/754880/9531745/e9b3354c-4d07-11e5-8e33-5a37eca5dfae.jpg)

Kind regards,
Jan

**Comment by TrueCryer** [comment]
What Windows do you use? Does directory C:/Users/Jan/.blendermada exist?

**Comment by janstieler** [comment]
Hi,
I use OSX 10.10.4
