### ISSUE TITLE
blendermada add-on

### ISSUE THREAD

**Issue by RichardoC** [TrueCryer/blendermada_client#10]
Thank you for an excellent piece of software. Unfortunately I'm having an issue, only 3 materials are available through the plug-in. They are blue glass, clear glass and gold. How can I fix this?

Thanks.

**Comment by marinaadlc** [comment]
I had the same problem; make sure you are in Cycles Render when accessing the materials, as only the ones you listed appear when in Blender Render

**Comment by TrueCryer** [comment]
Or add some more materials for Blender Render. Blendermada needs it)))
