### ISSUE TITLE
The client does not work with blender 2.8

### ISSUE THREAD

**Issue by jaccosteur** [TrueCryer/blendermada_client#20]
The client does not work yet with blender 2.8. After import of the plugin it shows the message that the plugin is not upgraded yet to 2.8.

![image](https://user-images.githubusercontent.com/8171438/49736988-e0fb0100-fc8b-11e8-9e1e-c936cc786b21.png)

**Comment by jaccosteur** [comment]
PS: Just updating the version number in the python script is not enough. ;-)

**Comment by foreachthing** [comment]
Uhm, so why is this issue closed?
It still does not work in 2.8.
